@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

interface fs as "FileSystem"
interface fr as "FileRepository"
interface f as "File"
interface c as "Command"
interface cp as "CommandParameter"

class flg as "Flag"

class t as "Touch"
class ls as "List"
class cd as "ChangeDirectory"
class mkdir as "MakeDirectory"
class rm as "Remove"
class pwd as "PrintWorkingDirectory"

class txtfr as "TextFileRepository"
class dr as "DirectoryRepository"

class cv as "CommandValidator"
class ce as "CommandExecuter"
class cli as "CommandLineInterface"

interface r as "Result"
class vc  as "ValidCommand" <<record>>
class ic as "InvalidCommand" <<record>>

vc .down.|> r
ic .down.|> r
cv -left-> r

class txtf as "TextFile"
class d as "Directory"

class vfs as "VirtualFileSystem"

cli -down-> cv
cv -right-> cp
cv -down-> ce

ce -left-> c
c <|-up- t
c <|-up- ls
c <|-down- cd
c <|-down- mkdir
c <|-down- rm
c <|-left- pwd

ce -right-> fs
fs <|-right- vfs
fs -down-> fr
fr -left-> f

f <|-right- d
f <|-left- txtf

txtfr -up-|> fr
txtfr -down-> txtf
dr -up-|> fr
dr -down-> d

cp <|-up- flg








@enduml